# Generated by Django 4.2.7 on 2023-11-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_createevent_eventuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='eventCreatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='eventModifyDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='createDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='modifyDate',
            field=models.DateTimeField(),
        ),
    ]
