# Generated by Django 4.2.7 on 2023-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_createevent_eventcreateddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='eventCreatedDate',
            field=models.DateTimeField(default='2023-11-28T14:00:33.603323+00:00'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='createDate',
            field=models.DateTimeField(default='2023-11-28T14:00:33.603323+00:00'),
        ),
    ]
