# Generated by Django 4.2.7 on 2023-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_createevent_eventcreateddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='eventCreatedDate',
            field=models.DateTimeField(default='2023-11-28T14:01:39.632840+00:00'),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='eventModifyDate',
            field=models.DateTimeField(default='2023-11-28T14:01:39.632840+00:00'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='createDate',
            field=models.DateTimeField(default='2023-11-28T14:01:39.633841+00:00'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='modifyDate',
            field=models.DateTimeField(default='2023-11-28T14:01:39.633841+00:00'),
        ),
    ]
