# Generated by Django 4.2.7 on 2023-11-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_createevent_eventcreateddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='eventCreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='eventModifyDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='modifyDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
