# Generated by Django 4.2.7 on 2023-11-28 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_createevent_eventcreateddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='totalPerson',
            field=models.IntegerField(max_length=2, validators=[django.core.validators.MaxLengthValidator(limit_value=2)]),
        ),
    ]
