# Generated by Django 4.2.7 on 2023-11-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_eventregistration_totalperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='totalPerson',
            field=models.IntegerField(),
        ),
    ]
